#!/bin/bash

if [ -z "$ANDROID_DEVICES" ]; then
  echo "ANDROID_DEVICES not set"
  exit 0
fi

if [ ! -d /opt/gcm-trigger ]; then
  git clone https://github.com/chteuchteu/Munin-for-Android-GCM-Trigger.git /opt/gcm-trigger
fi

chmod 755 /usr/local/bin/generate_devices.py
/usr/local/bin/generate_devices.py

cat << "EOF" > /etc/munin/munin-conf.d/gcm-trigger.conf
# Munin for Android notifications
# Configure script location & args
contact.munin_for_android.command /opt/gcm-trigger/main.py

# Set infos format
contact.munin_for_android.text  <alert group="${var:group}" host="${var:host}"\
  graph_category="${var:graph_category}" graph_title="${var:graph_title}" >\
  ${loop< >:wfields <warning label="${var:label}" value="${var:value}"\
    w="${var:wrange}" c="${var:crange}" extra="${var:extinfo}" /> }\
  ${loop< >:cfields <critical label="${var:label}" value="${var:value}"\
    w="${var:wrange}" c="${var:crange}" extra="${var:extinfo}" /> }\
  ${loop< >:ufields <unknown label="${var:label}" value="${var:value}"\
    w="${var:wrange}" c="${var:crange}" extra="${var:extinfo}" /> }\
  </alert>
EOF

if [ -n "$ANDROID_ALWAYS_TRIGGER" ]; then
  echo 'contact.munin_for_android.always_send warning critical' >> /etc/munin/munin.conf.d/gcm-trigger.conf
fi
